<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TweetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function allExceptUser($userId) {

        $qb = $this->createQueryBuilder('users');

        $qb->where('users.id != :userId')
            ->setParameter('userId', $userId);

        return $qb->getQuery()
            ->getResult();
    }


}
